### ISSUE TITLE
Добавить фичу SelectAll или SelStart-SelEnd

### ISSUE THREAD

**Issue by vectoris** [AlexanderBagel/FWHexView#1]
Добавите плз SelectAll или SelStart-SelEnd, спасибо.

**Comment by AlexanderBagel** [comment]
Добавлю, но позже, сейчас компонент в разобраном виде находится и его разработка временно приостановлена. Когда дойдут руки до его дальнейшего продвижения - сделаю.
В качестве временного решения можно вынести в паблик FSelStart + FSelEnd и назначать их руками с последующей инвалидацией.
